### ISSUE TITLE
自我评估

### ISSUE THREAD

**Issue by libchaos** [SniperM99/Team-DeepEye-kaggle#1]
1. Github 操作较为熟悉
2. ML 刚学习到线性回归
3. DL 还没开始深入接触，略有了解
4. 日常使用语言Python，node.js
5. 没有kaggle比赛经验

**Comment by SniperM99** [comment]
> 1. Github 操作较为熟悉
> 2. ML 刚学习到线性回归
> 3. DL 还没开始深入接触，略有了解
> 4. 日常使用语言Python，node.js
> 5. 没有kaggle比赛经验

github交流应该问题不大, python熟悉的话,可以进行特征工程相关方面的协作
kaggle 建议先自己去把泰坦尼克号之灾以及mnist手写体的比赛独立完成了, 对kaggle的比赛模式熟悉下.

**Comment by SniperM99** [comment]
问题不大, 我将添加你为本仓库的协作者进行协作, 请认真阅读首页的README.md文件,熟知之后的文件提交格式.如果没有其他问题,请关闭本次issues

**Comment by libchaos** [comment]
好的，谢谢建议
