### ISSUE TITLE
自我评估

### ISSUE THREAD

**Issue by zachary1992** [SniperM99/Team-DeepEye-kaggle#2]
1.硕士实习期间做过基于OpenCv和OpenCL的目标识别和优化的项目,熟悉C/C++编程,GPU并行编程,熟悉一些机器学习算法.
2.自学python,正在复习数学基础知识,学习机器学习.
3.目前在紫光展锐做Android方面的工作,熟悉Java编程.

**Comment by SniperM99** [comment]
> 1.硕士实习期间做过基于OpenCv和OpenCL的目标识别和优化的项目,熟悉C/C++编程,GPU并行编程,熟悉一些机器学习算法

great, 可以长期一起参赛, 进行CV方面的深度合作

**Comment by SniperM99** [comment]
已添加协作者, https://github.com/SniperM99/Team-DeepEye-kaggle/invitations 请进行确认. 
本次issues将关闭

**Comment by zachary1992** [comment]
ok!平时用基本用git + gerrit提交代码,github用的butaishulian. qing duo zhi jiao.
